name: AutoPlacePatch
version: '${project.version}'
main: com.quadflame.autoplacepatch.AutoPlacePatch
commands:
  autoplacepatch:
    description: Main command for AutoPlacePatch
    permission: autoplacepatch.command
    aliases:
    - app